drop table if exists FILMS_GENRES;
drop table if exists FILMS_LIKES;
drop table if exists FILMS;
drop table if exists FRIENDS_LIST;
drop table if exists GENRES;
drop table if exists RATINGS;
drop table if exists USERS;

CREATE TABLE IF NOT EXISTS ratings
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100),
    description  varchar(200),
    release_date date,
    duration     int,
    rating_id    varchar(4) REFERENCES ratings (id)
);

create unique index if not exists film_id_index on films (id);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films_genres
(
    genre_id varchar references genres (id),
    film_id  integer references films (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    text,
    login    text,
    name     text,
    birthday date
);

create unique index if not exists user_id_index on users (id);

CREATE TABLE IF NOT EXISTS films_likes
(
    film_id      integer references films (id),
    like_user_id integer references users (id)
);

CREATE TABLE IF NOT EXISTS friends_list
(
    user_id   integer references users (id),
    friend_id integer references users (id)
);